ERROR:2017-03-05 17:44:22,656-com.citywar.dice.db.DBPool-1 [main]
[ DBPool : DBPool ] 
java.sql.SQLException: Unable to open a test connection to the given database. JDBC url = jdbc:mysql://127.0.0.1:3306/db_citywar?characterEncoding=utf-8, username = root. Terminating connection pool. Original Exception: ------
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1075)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:920)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4000)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1285)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:787)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:357)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:256)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:305)
	at com.citywar.dice.db.DBPool.<init>(DBPool.java:108)
	at com.citywar.dice.db.DBPoolManager.createPools(DBPoolManager.java:175)
	at com.citywar.dice.db.DBPoolManager.init(DBPoolManager.java:134)
	at com.citywar.dice.db.DBPoolManager.<init>(DBPoolManager.java:40)
	at com.citywar.dice.db.DBPoolManager.getInstance(DBPoolManager.java:62)
	at com.citywar.dice.db.DBManager.initConfig(DBManager.java:51)
	at com.citywar.GameServer.start(GameServer.java:185)
	at com.citywar.GameServer.main(GameServer.java:153)
------

	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:312)
	at com.citywar.dice.db.DBPool.<init>(DBPool.java:108)
	at com.citywar.dice.db.DBPoolManager.createPools(DBPoolManager.java:175)
	at com.citywar.dice.db.DBPoolManager.init(DBPoolManager.java:134)
	at com.citywar.dice.db.DBPoolManager.<init>(DBPoolManager.java:40)
	at com.citywar.dice.db.DBPoolManager.getInstance(DBPoolManager.java:62)
	at com.citywar.dice.db.DBManager.initConfig(DBManager.java:51)
	at com.citywar.GameServer.start(GameServer.java:185)
	at com.citywar.GameServer.main(GameServer.java:153)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1075)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:920)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4000)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1285)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:787)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:357)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:256)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:305)
	... 8 more
ERROR:2017-03-05 17:44:22,938-com.citywar.dice.db.DBManager-283[main]
[DataBase] 提示消息:没有可用的数据库连接池; 错误描述:null 
ERROR:2017-03-05 17:44:22,960-com.citywar.dice.db.DBManager-305[main]
[DataBase] 提示消息:没有可用的数据库连接池; 错误描述:null 
ERROR:2017-03-05 17:44:22,961-com.citywar.dice.db.DBManager-306[main]
[DataBase] 提示消息:没有可用的数据库连接池; 错误描述:null 
ERROR:2017-03-05 17:44:22,961-com.citywar.manager.ItemMgr-306[main]
ItemMgr reload exception:java.lang.NullPointerException 
ERROR:2017-03-05 17:44:22,961-com.citywar.BaseServer-306[main]
initialize CardMgr failed 
ERROR:2017-03-05 21:46:24,428-com.citywar.dice.db.DBManager-96[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:23' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:24,680-com.citywar.dice.db.DBManager-348[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:23' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:24,784-com.citywar.dice.db.DBManager-452[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:24,925-com.citywar.dice.db.DBManager-593[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:24,931-com.citywar.dice.db.DBManager-599[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:24,970-com.citywar.dice.db.DBManager-638[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:24,975-com.citywar.dice.db.DBManager-643[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:24,977-com.citywar.dice.db.DBManager-645[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:24,983-com.citywar.dice.db.DBManager-651[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:24,987-com.citywar.dice.db.DBManager-655[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:24,993-com.citywar.dice.db.DBManager-661[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:24,995-com.citywar.dice.db.DBManager-663[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,002-com.citywar.dice.db.DBManager-670[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,004-com.citywar.dice.db.DBManager-672[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:24' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,097-com.citywar.dice.db.DBManager-765[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,098-com.citywar.dice.db.DBManager-766[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,104-com.citywar.dice.db.DBManager-772[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,106-com.citywar.dice.db.DBManager-774[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,110-com.citywar.dice.db.DBManager-778[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,112-com.citywar.dice.db.DBManager-780[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,116-com.citywar.dice.db.DBManager-784[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,118-com.citywar.dice.db.DBManager-786[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,122-com.citywar.dice.db.DBManager-790[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,123-com.citywar.dice.db.DBManager-791[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,175-com.citywar.dice.db.DBManager-843[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,177-com.citywar.dice.db.DBManager-845[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,181-com.citywar.dice.db.DBManager-849[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,183-com.citywar.dice.db.DBManager-851[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,186-com.citywar.dice.db.DBManager-854[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,188-com.citywar.dice.db.DBManager-856[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,193-com.citywar.dice.db.DBManager-861[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,194-com.citywar.dice.db.DBManager-862[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,198-com.citywar.dice.db.DBManager-866[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,200-com.citywar.dice.db.DBManager-868[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,204-com.citywar.dice.db.DBManager-872[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,206-com.citywar.dice.db.DBManager-874[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,211-com.citywar.dice.db.DBManager-879[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,213-com.citywar.dice.db.DBManager-881[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,218-com.citywar.dice.db.DBManager-886[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,220-com.citywar.dice.db.DBManager-888[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,228-com.citywar.dice.db.DBManager-896[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,231-com.citywar.dice.db.DBManager-899[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,236-com.citywar.dice.db.DBManager-904[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,237-com.citywar.dice.db.DBManager-905[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,241-com.citywar.dice.db.DBManager-909[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,243-com.citywar.dice.db.DBManager-911[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,247-com.citywar.dice.db.DBManager-915[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,249-com.citywar.dice.db.DBManager-917[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,252-com.citywar.dice.db.DBManager-920[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,253-com.citywar.dice.db.DBManager-921[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,258-com.citywar.dice.db.DBManager-926[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,259-com.citywar.dice.db.DBManager-927[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,262-com.citywar.dice.db.DBManager-930[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,264-com.citywar.dice.db.DBManager-932[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,268-com.citywar.dice.db.DBManager-936[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,269-com.citywar.dice.db.DBManager-937[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,274-com.citywar.dice.db.DBManager-942[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,276-com.citywar.dice.db.DBManager-944[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,281-com.citywar.dice.db.DBManager-949[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,282-com.citywar.dice.db.DBManager-950[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,286-com.citywar.dice.db.DBManager-954[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,287-com.citywar.dice.db.DBManager-955[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,292-com.citywar.dice.db.DBManager-960[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,294-com.citywar.dice.db.DBManager-962[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,298-com.citywar.dice.db.DBManager-966[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,300-com.citywar.dice.db.DBManager-968[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,304-com.citywar.dice.db.DBManager-972[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,306-com.citywar.dice.db.DBManager-974[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
ERROR:2017-03-05 21:46:25,309-com.citywar.dice.db.DBManager-977[pool-12-thread-1]
[ DBManager : executeNoneQuery ] 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2398)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2316)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2301)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
	at com.citywar.dice.db.DBManager.executeNoneQuery(DBManager.java:388)
	at com.citywar.dice.dao.impl.FiveMinSummaryDaoImpl.insert(FiveMinSummaryDaoImpl.java:38)
	at com.citywar.bll.FiveMinSummaryBussiness.addFiveMinSummaryInfo(FiveMinSummaryBussiness.java:10)
	at com.citywar.manager.GameServerTimerMgr$FiveMinSummaryTask.run(GameServerTimerMgr.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
ERROR:2017-03-05 21:46:25,311-com.citywar.dice.db.DBManager-979[pool-12-thread-1]
[DataBase] 提示消息:当前Sql语句出错; 错误描述:Duplicate entry '1-2017-03-05 21:46:25' for key 'PRIMARY'; 当前状态:调用Sql语句insert into t_5_min(count_date, sub_id , reg, online) values(?,?,?,?)出错 
